language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 0.6.2
  - 0.6

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SoilTracers")'
  - julia --check-bounds=yes -e 'Pkg.test("SoilTracers", coverage=true)'

# push coverage results
after_success:
  - julia -e 'cd(Pkg.dir("SoilTracers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
